name: Python CI for Tic Tac Toe

on:
  push:
    branches: [Development]
  pull_request:
    branches: [Development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 tic_tac_toe.py

    - name: Run syntax check (no execution)
      run: |
        python -m py_compile tic_tac_toe.py

